Omit image in postgrescluster specs
The image we specified does not have the server sub-command.

```
naved@Naveds-MacBook-Pro ~ % oc logs netbox-pgha1-bc2z-0 pgbackrest
ERROR: [048]: invalid command 'server'
```
due to which the backups don't work.

and acccording to the documentation[1] if we don't specify the image it will
get that from the operator.

[1] https://access.crunchydata.com/documentation/postgres-operator/5.1.0/references/crd/#postgrescluster

closes #592